version: '2'
services:
 app:
  image: busybox
  container_name: 'app'
  volumes:
   - /var/lib/postgresql/data

 postgres:
  image: reflet/debian8-postgres91
  container_name: 'postgres'
  env_file: .env.postgres
  volumes:
      - ./initdb.postgres:/docker-entrypoint-initdb.d/
  ports:
      - "5432:5432"
  volumes_from:
      - app

