version: '2'
services:
 postgres:
  image: reflet/debian8-postgres91
  container_name: 'postgres'
  env_file: .env.postgres
  volumes:
   - ./initdb.postgres:/docker-entrypoint-initdb.d/
   - db-data:/var/lib/postgresql/data
  ports:
   - "5432:5432"

volumes:
  db-data:
    driver_opts:
      type: none
      device: /home/vagrant/test/data/postgres/
      o: bind

